pipeline {
    agent any
    stages {
	    
	    stage('clean ws') { 
		    steps {
			    cleanWs()
		    }
	    }	   
	    
	    stage("01 git checkout"){
		    steps {
			    git 'https://github.com/xt4k/pipeExamples2'
		    }
	    }
	    
	    stage('02 run auto-test_in_Maven') {
		    steps {
			    withMaven( globalMavenSettingsConfig: '2115a339-7bf0-4a98-8e0c-6e2742b17571',jdk: 'jdk-8', maven: 'maven') {
				    sh 'mvn -Dbrowser=chrome  -Dmaven.test.failure.ignore -Dsuite=common clean test'
			    }
		    }		
	    }
	    
	    stage("allure report add") {
		    steps{
			    allure includeProperties: false, jdk: '', results: [[path: 'target/allure-results']]
		    }
	    }
	    
	    stage ("send notif to telegram") {
		    steps {
			    telegramSend(message: "BUILD_TAG: ${BUILD_TAG} completed22", chatId: -1001424392176)
		    }
	    }

	    stage ("send tg") {
        		    steps {
        		        sh 'java  "-Dchat.id=-1001424392176" "-Dbot.token=1624369115:AAFskvWdGdr1d47B-b5Q7ZHvHwNsn02hPCo" "-Dproject.name=${JOB_BASE_NAME}" "-Dbuild.launch.name=Some release 2.0" "-Dbuild.env=https://prod.your.site" "-Dbuild.report.link=${BUILD_URL}" "-Dlang=en" "-Denable.chart=true" "-Dallure.report.folder=./allure-report/" -jar allure-notifications-2.2.2.jar'
        		    }
        }

        stage ("19 send chart to email") {
        			steps {
        			echo 'here will be sending to e-mail'
              		}
                }
    }
}
